### ISSUE TITLE
🐛 BUG: calling get on kv from different service environment throws empty error

### ISSUE THREAD

**Issue by flocbit** [cloudflare/wrangler2#1098]
### What version of `Wrangler` are you using?

2.0.6

### What operating system are you using?

Mac

### Describe the Bug

Trying to access KV entry like so:

``` typescript
try {
        stringifiedFirebaseJwkPublicKeys = await AUTHENTICATION.get(
            FIREBASE_AUTHENTICATION_JWK_PUBLIC_KEYS
        )
    } catch (error) {
        throw new UserError({
            message: ErrorMessages.Unauthorized,
            code: 403,
            loggingDetails: {
                title: LogEventTitles.Unauthorized,
                value: {
                    description:
                        'Could not retrieve jwk public keys from key value storage.',
                    error,
                },
            },
        })
    }
```

When using service environment "production" everything is working as expected but when switching to others an empty error is thrown as seen in the following log message:

```
{
      "message": [
        "Unauthorized",
        {
          "description": "Could not retrieve jwk public keys from key value storage.",
          "error": {}
        }
      ],
      "level": "log",
      "timestamp": 1653389788990
    }
```

I could not find any documentation as to wether KV is safe to use across service environments. Please let me know if that should not be the case.

**Comment by petebacondarwin** [comment]
Hi @flocbit - can you provide some more information to help diagnose this problem.

1. What is the exact command you use to publish this?
2. Do you have legacy-env turned on or off?
3. Can you provide the wrangler.toml (suitably redacted) that you are using?

**Comment by flocbit** [comment]
Hi @petebacondarwin,

1. I use `wrangler publish` without any parameters
2. Where do I check that? I have recently updated to wrangler2 and my toml file does not include any references to legacy environments.
3. See my wrangler.toml file below

```toml

name = "xxx"
account_id = "xxx"
workers_dev = false
compatibility_date = "2022-05-20"
main = "./src/index.ts"

kv_namespaces = [
  { binding = "AUTHENTICATION", id = "xxx", preview_id = "xxx" }
]

[vars]
FIREBASE_PROJECT_ID = "xxx"

[build]
command = "yarn && yarn build"

```

**Comment by flocbit** [comment]
Update:

Seems like KV namespaces between service environments are indeed NOT shared.

At least that's what my newest logs seem to indicate:

```
{
      "message": [
        "Unauthorized",
        {
          "description": "Could not retrieve jwk public keys from key value storage.",
          "error": "AUTHENTICATION is not defined"
        }
      ],
      "level": "log",
      "timestamp": 1653392968233
    }
```

Is that intentional and how could I set up different KVs for different service environments?

**Comment by petebacondarwin** [comment]
Some notes and questions:
- legacy_env is true by default so unless you set it to false (via `wrangler.toml` or `--legacy-env=false` command line arg) Wrangler will be using the old-style environments where a completely new Worker is deployed with the environment name appended to the Worker name.
- How do you switch to a different service environment? Do you use the `--env` flag?

**Comment by petebacondarwin** [comment]
Be aware that "service environments" are not yet stable, and so use them in the knowledge that some things may change.
You can publish such environments via Wrangler, which may also be the only way to setup the bindings to things like KV correctly. I suspect that deploying from one environment to another that has never been deployed via Wrangler will not have the correct bindings in place.

Here is how your `wrangler.toml` might look to get this to work:

```toml
name = "xxx"
account_id = "xxx"
workers_dev = false
compatibility_date = "2022-05-20"
main = "./src/index.ts"
# Tell Wrangler that you want to use "service environments".
legacy_env=false

kv_namespaces = [
  { binding = "AUTHENTICATION", id = "xxx", preview_id = "xxx" }
]

[vars]
FIREBASE_PROJECT_ID = "xxx"

[build]
command = "yarn && yarn build"

# Define bindings and vars for a "staging" environment
# (note that bindings and vars are not inherited from the top level
# and must be explicitly set for each environment).
[env.staging.kv_namespaces] = [
  { binding = "AUTHENTICATION", id = "xxx", preview_id = "xxx" }
]
[env.staging.vars]
FIREBASE_PROJECT_ID = "xxx"
```

Then you should be able to deploy using

```bash
npx wrangler publish --env=staging
```
