### ISSUE TITLE
🐛 BUG: "node_compat = true" is being ignored [Node builtin module import while Node compatibility is disabled]

### ISSUE THREAD

**Issue by rauleite** [cloudflare/wrangler2#1150]
### What version of `Wrangler` are you using?

2.0.7

### What operating system are you using?

Linux

### Describe the Bug

**Error:**
[plugin: checkForNodeBuiltins] Detected a Node builtin module import while Node compatibility is disabled.
Add node_compat = true to your wrangler.toml file to enable Node compatibility.

But, I already had add the **node_compat** on **wrangler.toml**:
```toml
name = "api"
compatibility_date = "2022-05-16"
account_id = "1b5b99f85df2ff3830dfec7cb7cee2d9"
workers_dev = true

# Seems it's not working
node_compat = true

# --- STAGING ---
[env.staging]
  main = "dist/bundle.js"
  [dev]
    # ip = "192.168.0.103"
    # @default `8787`

[env.staging.build]
  command = "pnpm run build"  
```

The file that throws the error:

_src/index.ts_
```javascript
import puppeteer from 'puppeteer-extra'
import StealthPlugin from 'puppeteer-extra-plugin-stealth'

/**
Line with that throws the error:
PS. works only if comment this line
*/
puppeteer.use(StealthPlugin())

addEventListener("fetch", (event) => {
  //@ts-ignore
  event.respondWith(handleRequest(event.request));
});

//@ts-ignore
async function handleRequest(request) {
  return new Response("Hello worker!", {
    headers: { "content-type": "text/plain" },
  });
}
```
I'm using with webpack:

_package.json_
```json
"build": "webpack"
"dev": "wrangler dev -e staging --local"
```

_webpack.config.cjs_
```javascript
module.exports = {
  target: "webworker",
  mode: "development",
  devtool: 'cheap-module-source-map',
  entry: './src/index.ts',
  /*
    It throws with or without 'externals' and 'externalsPresets'
  */
  externals: [
    nodeExternals()
  ],
  externalsPresets: {
    node: true
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },

  resolve: {
    extensions: ['.tsx', '.ts', '.js'],
  },
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist'),
  }
}
```

My repo with minimal code for error reproduction:
https://github.com/rauleite/issue

- _Node: 17.9.0_
- _pnpm: 7.1.6_
