### ISSUE TITLE
 Could not route to  [..] upload-token, perhaps your object identifier is invalid? [code: 7003]     No route for that URI [code: 7000]

### ISSUE THREAD

**Issue by klausbreyer** [cloudflare/wrangler2#1177]
I try to publish to a pages project by using Account Id + API Token within a github action: 

``` 
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish src --project-name=unixtimeapp

```

This fails with: 

``` 
Could not route to /accounts/***/pages/projects/unixtimeapp/upload-token, perhaps your object identifier is invalid? [code: 7003]
    No route for that URI [code: 7000]
```

API Token got this permission:

```
All accounts - Cloudflare Pages:Edit
```

I am not sure, if it an issue of the API tokens permission or of wrangler itself. I am just here, because the output from the github action pointed me to create an issue here. :)
