### ISSUE TITLE
🐛 BUG:  [ERROR] Received a malformed response from the API

### ISSUE THREAD

**Issue by klausbreyer** [cloudflare/wrangler2#1220]
### What version of `Wrangler` are you using?

2.0.8

### What operating system are you using?

mac

### Describe the Bug

After 1 successfull publish on the main branch, now I only receive errors. 
```

✘ [ERROR] Received a malformed response from the API

  
  POST /pages/assets/check-missing -> 500 Internal Server Error
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new/choose
```

Running it by CLI: 
```
yarn run wrangler pages publish src --project-name=unixtimeapp
```

And on my github action as well: 
```
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Run your project's build step
      # - name: Build
      #   run: npm install && npm run build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: unixtimeapp # e.g. 'my-project'
          directory: src # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
```

Everything worked like a charm, for a single commit. Locally and in the Action as well. 
I changed nothing. Same API_TOKEN. No changes in ACL. 
I think it stopped working after I had a successfull production commit.
