### ISSUE TITLE
🚀 Feature Request: setting environment variable for pages

### ISSUE THREAD

**Issue by Plausible0Bug** [cloudflare/wrangler2#1368]
### Describe the solution

I'm currently migrating some worker sites that feels more appropriate for pages.

I have a following toml file for one of the worker sites:

```
name = "sample-page"

compatibility_date = "2022-05-28"

[vars]
RELEASE = "unknown" # RELEASE should be injected during prebuild
```

Which will figure out release version and inject into `wrangler.toml` during prebuild script.

However according to https://github.com/cloudflare/wrangler2/blob/b2c2c2b86278734f9ddf398dbb93c06ffcc0d5b0/packages/wrangler/src/pages/publish.tsx#L63
The `wrangler.toml` simply doesn't apply to pages when publishing using wrangler.
According to https://developers.cloudflare.com/workers/wrangler/commands/#pages there are no wrangler command to modify environment variables for a specific cloudflare pages project.

I use [wrangler](https://github.com/cloudflare/wrangler-action) github action because of our monorepo setup, here is our workflow configuration:
```
name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Filter changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            sample-page:
              - 'sample-page/**'
      - name: Publish sample-page
        if: steps.changes.outputs.sample-page == 'true'
        uses: cloudflare/wrangler-action@2.0.0
        with:
          workingDirectory: 'sample-page'
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: npm i && npm run build
          command: pages publish ./public --project-name=sample-page
```

Thank you in advance for your help.
