### ISSUE TITLE
🐛 BUG: Interactive metrics makes CircleCI jobs fails (timeout)

### ISSUE THREAD

**Issue by thibault-deriv** [cloudflare/wrangler2#1480]
### What version of `Wrangler` are you using?

2.0.21

### What operating system are you using?

Linux 

### Describe the Bug

Hello :smiley: 

First, thank you for wrangler2 :+1: 

With wrangler@2.0.21, the client is asking for (y/n) about metrics that makes CircleCI fails:
```bash
🌏  Uploading... (1/1)

✨ Success! Uploaded 1 files (2.35 sec)

✨ Deployment complete! Take a peek over at https://4a05b732.interactive-metrics.pages.dev
▲ [WARNING] Unrecognised input: `


Would you like to help improve Wrangler by sending usage metrics to Cloudflare?
(y/n)


Too long with no output (exceeded 10m0s): context deadline exceeded
```

# 2.0.21
![interactive](https://user-images.githubusercontent.com/104425314/179222261-8fd42243-1945-4f19-b2e8-5e2b7b4da9b4.png)

# 2.0.19
![not-interactive](https://user-images.githubusercontent.com/104425314/179222300-5c9f9dae-75ad-4019-a3ab-767e5ca57c91.png)

You can highlight this issue with this CircleCI config (add `CLOUDFLARE_API_TOKEN` and `CLOUDFLARE_ACCOUNT_ID` secrets in settings):
```yml
version: 2.1
  
jobs:
  not_interactive:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run:
          name: "Publish to cloudflare pages (not interactive)"
          command: |
            npm i wrangler@2.0.19
            mkdir public
            cd public
            echo "Hello not interactive" >> index.html
            npx wrangler pages publish . --project-name=interactive-metrics --branch=not
  interactive:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run:
          name: "Publish to cloudflare pages (interactive)"
          command: |
            npm i wrangler@2.0.21
            mkdir public
            cd public
            echo "Hello interactive" >> index.html
            npx wrangler pages publish . --project-name=interactive-metrics --branch=main
 
workflows:
  release_not_interactive:
    jobs:
      - not_interactive:
          filters:
            branches:
              only: /^main$/
  release_interactive:
    jobs:
      - interactive:
          filters:
            branches:
              only: /^main$/
```

wrangler@2.0.19 is fine.

# 2.0.21 versus 2.0.19
![interactive-not-interactive](https://user-images.githubusercontent.com/104425314/179222423-bae40320-6d45-4b7e-b2f3-e9d1dd73881b.png)

I see from documentation that we can configure the option in wrangler.toml, but I think it would be better to do not ask at all when detecting it's running in CI (like `npx` does, no idea how exactly) and even in a more general manner probably to do not make wrangler fails for such a *side* tasks (upload was OK).

Thank you in advance!

Thibault
