### ISSUE TITLE
🐛 BUG: wrangler2 tries to open a browser to authenticate in CircleCI

### ISSUE THREAD

**Issue by thibault-deriv** [cloudflare/wrangler2#1593]
### What version of `Wrangler` are you using?

2.0.23

### What operating system are you using?

Linux

### Describe the Bug

When publishing in CircleCI without providing a `CLOUDFLARE_API_TOKEN`, it tries to open a browser. It timeouts quickly, but I suppose ideally it should not try to open a browser at all.

## Demo
```yml
version: 2.1
  
jobs:
  browser:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run:
          name: "Publish to cloudflare pages (KO)"
          command: |
            npm i wrangler@2.0.23
            mkdir public
            cd public
            echo "Hello browser" >> index.html
            CLOUDFLARE_ACCOUNT_ID=abcd npx wrangler pages publish . --project-name=open-browser-in-circleci --branch=main
workflows:
  release_browser:
    jobs:
      - browser:
          filters:
            branches:
              only: /^main$/
```

Will produce:
![ko-browser-circleci](https://user-images.githubusercontent.com/104425314/182201709-535c5d4e-fc9f-4e28-8fa9-541490916610.png)
