### ISSUE TITLE
🐛 BUG: CircleCI deploy pages

### ISSUE THREAD

**Issue by goldylucks** [cloudflare/wrangler2#1657]
### What version of `Wrangler` are you using?

2.0.25

### What operating system are you using?

Ubuntu 20.04

### Describe the Bug

When I'm running deploy locally:
```
CLOUDFLARE_ACCOUNT_ID=********** npx wrangler pages publish dist/apps/breath --project-name=breathe
```

It works fine.

However in circle ci when I set it through like the docs:
```
  deploy:
    docker:
      - image: cimg/node:18.7.0
    environment:
      CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
      CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
    steps:
      - checkout
      - bt-yarn-install
      - run: yarn build
      - setup_remote_docker:
          version: 20.10.14
      - run: yarn deploy
```

I'm getting this error:
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/6963212/184072660-2d89df91-e460-446c-8831-56c2083317a8.png">

I've set the environment variables on Circle CI as per the docs

**Comment by sidharthachatterjee** [comment]
Hiya! We just reproduced this and figured out what's wrong. You need to remove the `environment` block in your config and ensure the variables are declared in your project settings in CircleCI. 

```
deploy:
    docker:
      - image: cimg/node:18.7.0
    steps:
      - checkout
      - bt-yarn-install
      - run: yarn build
      - setup_remote_docker:
          version: 20.10.14
      - run: yarn deploy
```

The above should work! Cheers. Closing this for now since it isn't a wrangler bug per se. Also updating our documentation in https://github.com/cloudflare/cloudflare-docs/pull/5607

Thanks!
