### ISSUE TITLE
pages dev proxy doesn't work with Vite CSS HMR

### ISSUE THREAD

**Issue by connorads** [cloudflare/wrangler2#169]
Tried using `astro` (which uses `vite`) with `wrangler pages dev` and it mostly works except the CSS
`npx wrangler pages dev --proxy 3000 -- npx astro dev`

`vite` [http://localhost:3000](http://localhost:3000) working ✅ `global.css` contains CSS
![image](https://user-images.githubusercontent.com/10026538/147413891-5f99c481-e01e-4c0c-bf2a-6bdba1d763b7.png)
`wrangler` [http://127.0.0.1:8788](http://127.0.0.1:8788) not working ❌ `global.css` contains JavaScript
![image](https://user-images.githubusercontent.com/10026538/147417371-95296b96-87cd-4ad9-a8d9-276e48b9b090.png)

### How to reproduce

1. Clone https://github.com/connorads/connoradams.co.uk/commit/b9bd321342d6531a3f2e3374d108bb47801a86fd
2. `npm install`
3. `npx wrangler pages dev --proxy 3000 -- npx astro dev`
4. Compare results between `vite` and `wrangler` proxy
Look at `Developer Tools > Sources > src/styles/global.css`
    - `vite` [http://localhost:3000](http://localhost:3000)
    - `wrangler` [http://127.0.0.1:8788](http://127.0.0.1:8788)

```css
/*
vite - http://localhost:3000
src/styles/global.css
*/

* {
	box-sizing: border-box;
	margin: 0;
}

:root {
	font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;
	font-size: 1rem;
	--user-font-scale: 1rem - 16px;
	font-size: clamp(0.875rem, 0.4626rem + 1.0309vw + var(--user-font-scale), 1.125rem);
}

body {
	padding: 4rem 2rem;
	width: 100%;
	min-height: 100vh;
	display: grid;
	justify-content: center;
	background: #f9fafb;
	color: #111827;
}

@media (prefers-color-scheme: dark) {
	body {
		background: #111827;
		color: #fff;
	}
}

```

```javascript
// wrangler - http://127.0.0.1:8788
// src/styles/global.css

import { createHotContext as __vite__createHotContext } from "/@vite/client";import.meta.hot = __vite__createHotContext("/src/styles/global.css");import { updateStyle, removeStyle } from "/@vite/client"
const id = "/path/to/files/src/styles/global.css"
const css = "* {\n\tbox-sizing: border-box;\n\tmargin: 0;\n}\n\n:root {\n\tfont-family: -apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji;\n\tfont-size: 1rem;\n\t--user-font-scale: 1rem - 16px;\n\tfont-size: clamp(0.875rem, 0.4626rem + 1.0309vw + var(--user-font-scale), 1.125rem);\n}\n\nbody {\n\tpadding: 4rem 2rem;\n\twidth: 100%;\n\tmin-height: 100vh;\n\tdisplay: grid;\n\tjustify-content: center;\n\tbackground: #f9fafb;\n\tcolor: #111827;\n}\n\n@media (prefers-color-scheme: dark) {\n\tbody {\n\t\tbackground: #111827;\n\t\tcolor: #fff;\n\t}\n}\n"
updateStyle(id, css)
import.meta.hot.accept()
export default css
import.meta.hot.prune(() => removeStyle(id))
```
