### ISSUE TITLE
🚀 Feature Request: Wrangler secret put for non-production environments.

### ISSUE THREAD

**Issue by Skye-31** [cloudflare/wrangler2#1715]
### Describe the solution

Currently, when using `wrangler secret put`, it always uses the production environment, with no way to allow it to put to other environments. This is a problem, as due to the way environments are currently created (as a separate worker), there's no way to programatically put these secrets on the correct environment without you calling the API yourself. 

If the proper environments solution is coming soon, this isn't a problem, however in it's current form, it's somewhat unusable. For additional context, this is being done using the wrangler action like so:
```yml
- name: Publish
  uses: cloudflare/wrangler-action@2.0.0
  with:
    apiToken: ${{ secrets.CF_API_TOKEN }}
    command: publish --env staging
    secrets: |
      ABC
  env:
    ABC: ${{ secrets.ABC }}
```
