### ISSUE TITLE
🐛 BUG: Wrangler publish returning generic error: Authentication error [code: 10000]

### ISSUE THREAD

**Issue by gc-kismael** [cloudflare/wrangler2#1723]
### What version of `Wrangler` are you using?

2.0.27

### What operating system are you using?

Mac/Linux

### Describe the Bug

I'm trying to build a CI/CD pipeline in CircleCI to publish a worker script to cloudflare, but it's failing in the pipeline.
It was working on my mac yesterday, but at the time of writing, it's not even working on my local.

(Side note: when it was working yesterday on my local, at times it was launching a browser window for me to login, even though I have been following https://developers.cloudflare.com/workers/wrangler/ci-cd/ )

my toml file looks like this 
```toml
name = "wrangler"
main = "src/index.js"
compatibility_date = "2022-08-22"
account_id = "xxxx"

[vars]
CLOUDFLARE_API_TOKEN = "xxx"
NAME = "CanaryProcessCookie"
DRUPAL_URL = "xxxx"
NEXT_JS_URL = "xxxx"
DRUPAL_COOKIE = "drupal"
NEXT_JS_COOKIE = "next"
NEXT_JS_CANARY_WEIGHT = 0.5
```

(my api token has underscores in it, not sure if that's relevant)

My Api token has the following permissions
- cloudflare pages - Edit
- workers R2 storage - Edit
- Workers Tail - Read
- Workers KV Storage - Edit
- Workers Scripts - Edit (initially i had just this, i thought this was all i needed)
- Account Settings - Read

I have installed wrangler just within the scope of the project, so i am running the following command to publish:
`npx wrangler publish src/index.js --name worker-preprod `  

and i get this output/error:

Your worker has access to the following bindings:
- Vars:
  - CLOUDFLARE_API_TOKEN: "xxxx"
  - NAME: "CanaryProcessCookie"
  - DRUPAL_URL: "xxxx"
  - NEXT_JS_URL: "xxxx"
  - DRUPAL_COOKIE: "drupal"
  - NEXT_JS_COOKIE: "next"
  - NEXT_JS_CANARY_WEIGHT: "0.5"
Total Upload: 0.96 KiB / gzip: 0.46 KiB

✘ [ERROR] A request to the Cloudflare API (/accounts/xxxx/workers/scripts/worker-preprod) failed.

  Authentication error [code: 10000]

How come i'm not able to publish? and what does this error mean?

Any help is appreciated :) Thanks
