### ISSUE TITLE
How to disable local cache in dev mode

### ISSUE THREAD

**Issue by aliuq** [cloudflare/wrangler2#1817]
#### Describe the bug

Coding for a while, this url `localhost:8787` is not changed by any modified, e.g. wheh I comment belows if condition, it will keep the old result.

```ts
export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url)
    console.log(url.host);
    console.log(url.hostname);
    
    // if (url.host in regs) {
    // 	url.host = regs[url.host]
    // 	url.port = '80'
    // 	return proxy(url, request)
    // }
    return new Response("Hello World!");
  },
};
```

#### Environment and versions

Fill out the following information about your environment.

* operating system: `Windows 11`
* output of `wrangler -V`: `wrangler 2.0.23`
* output of `node -v`: `v16.14.2`
* content of `wrangler.toml`:
```toml
# wrangler.toml
name = "proxy-github"
main = "src/index.ts"
compatibility_date = "2022-07-31"
workers_dev = false
```
