### ISSUE TITLE
🐛 BUG: Configuring kv_namespaces as described in docs doesn't work

### ISSUE THREAD

**Issue by rozenmd** [cloudflare/wrangler2#1879]
### What version of `Wrangler` are you using?

2.1.3

### What operating system are you using?

Mac

### Describe the Bug

Docs here: https://developers.cloudflare.com/workers/wrangler/cli-wrangler/configuration/#kv_namespaces

Using this config:
```toml
kv_namespaces = [
  { binding = "FOO", id = "xxx", preview_id = "xxx" },
  { binding = "BAR", id = "xxx", preview_id = "xxx" }
]
```

Results in wrangler2 not printing these kv_namespaces. Instead, you have to use this format to get it working:
```toml
[[kv_namespaces]]
binding = "FOO"
preview_id = "xxx"
id = "xxx"

[[kv_namespaces]]
binding = "BAR"
preview_id = "xxx"
id = "xxx"
```

We should either fix this bug, or update the docs.
