### ISSUE TITLE
🐛 BUG: Wrangler dev fails when CF Access is enabled on `*.domain.tld`

### ISSUE THREAD

**Issue by Skye-31** [cloudflare/wrangler2#1906]
### What version of `Wrangler` are you using?

2.1.6

### What operating system are you using?

Windows (don't think it makes a difference here)

### Describe the Bug

1. Create a worker
2. Create a Cloudflare Access application, with routes `*.yourdomain.com` and `yourdomain.com`
3. Run `wrangler dev`, and attempt to visit your worker
4. Find the following error message ![image](https://user-images.githubusercontent.com/46286597/191810684-dbe06f06-91a6-4d92-be73-96be210b0472.png)

(worth noting this is also logged) 
![image](https://user-images.githubusercontent.com/46286597/191811285-2573059b-1757-4015-abc2-e8177f552142.png)

**Comment by cameron-robey** [comment]
Hey 👋 !

I've done some investigation into this, and I have been trying to reproduce this.

The steps I took:

1. Create a worker and add a custom domain to it in `wrangler.toml`
2. Create an access application with that domain
3. Run `npx wrangler dev`

Interestingly I am getting no errors in the console, but I get an `ERROR 1000: DNS points to prohibited IP` in browser.
Everything works ok with wrangler publish.

Firstly, could you provide some further steps for reproduction, or retrying this with a different domain?
Secondly, I think that it could be possible to pass through a token in our proxy server to allow `wrangler dev` to access Cloudflare Access applications - we will discuss this internally.

**Comment by Skye-31** [comment]
Relevant wrangler toml here
I believe this only occurs when the access policy explicitly covers `*.example.com`, as `wrangler dev` will then run on `somesubdomain.example.com`.
```toml
name = "core"
main = "src/index.ts"
compatibility_date = "2022-08-19"
account_id = "snip"

usage_model = "bundled"
d1_databases = [
	{ binding = "DB", database_name = "core", database_id = "snip", preview_database_id = "snip" }
]
routes = [
	{ pattern = "example.com/api*", zone_id = "snip" }
]
```
