### ISSUE TITLE
🚀 Feature Request: Deployment Strategies

### ISSUE THREAD

**Issue by d-gagne** [cloudflare/wrangler2#1997]
### Describe the solution

Problem: Currently, `wrangler publish` overwrites a previous script immediately, without an option for immediate rollback, or canary release.

Solution 1: Versioned deployments with activation
Set a flag in the toml to select versioned deployments. Each version of a script could published with a number suffix, like `helloWorld-2`, or with some other version metadata to allow you to roll back. Use of `wrangler publish` while using versioned deployments would deploy the new script, but not take over the route, until you use `wrangler activate helloWorld-2`. To roll back a release, it would just be `wrangler activate helloWorld-2`. There could be a setting in the toml for number of script versions to keep, so it could automatically clean up helloWorld-1 when you publish helloWorld-3.

Solution 2: Canary deployments
In the toml, set a flag to select canary deployments. This option also requires a plan that includes load balancers (and probably a new token permission to create/modify them). When publishing the first time, a load balancer will be created with one LB Pool, with one origin, which is pointed to the script version v1. It might be worth making a `wrangler lb create helloWorld` to set this up the first time, and put the LB ID in the toml. Once that is setup, it allows you to `wrangler activate helloWorld-2 --canary` which will add or update it as the second origin in that pool, with a weight of 5% (configurable in the toml maybe?).

Solution 3: Blue / Green
Probably easier than the above, not going to detail how it would work.

These are all possibilities now with custom API work, but it would be ideal if they were integrated into wrangler so everyone could take advantage of this.

**Comment by caass** [comment]
This is definitely something we're interested in supporting, but requires some work internally to make sure we do it right. In the meantime, have you looked into [service bindings](https://developers.cloudflare.com/workers/platform/bindings/about-service-bindings/)? You would be able to control your own deployment strategy by writing a simple worker that sits in front of your service and routes traffic based on your preferred method of deployment. For example, for a service `foo`:

```toml
# wrangler.toml
name = "foo-router"
main = "src/index.js"
compatability_date = "2022-10-10"

route = "example.org/foo/*"

services = [
  { binding = "FOO_PROD", service = "foo", environment = "production" },
  { binding = "FOO_STAGING", service = "foo", environment = "staging" },
  { binding = "FOO_DEV", service = "foo", environment = "development" }
]
```

```js
// src/index.js
export default {
  fetch: async (request, env) => {
    const randomNumber = Math.random();
    if (randomNumber < 0.01) {
      return env["FOO_DEV"].fetch(request);
    }

    if (randomNumber < 0.1) {
      return env["FOO_STAGING"].fetch(request);
    }

    return env["FOO_PROD"].fetch(request);
  },
};
```

You could potentially extend this further depending on your use-case and your desired deployment strategy. I'm going to close this issue for now as to really support this within wrangler we need to wait on the aforementioned internal changes. Hopefully this helps!
