### ISSUE TITLE
🐛 BUG: Received a malformed response from the API

### ISSUE THREAD

**Issue by Vapourium** [cloudflare/wrangler2#2069]
### What version of `Wrangler` are you using?

2.1.13

### What operating system are you using?

Linux

### Describe the Bug

Pushing my astro site locally from my windows machine seems to work, but whenever I use wrangler within a woodpecker pipeline, I get the following error:

```
✘ [ERROR] Received a malformed response from the API

<!DOCTYPE html>
<html lang="en-US">
<head>
<title>Just a moment...</title>
<meta http-equiv=... (length = 8651)

GET /accounts/********/pages/projects/vapour-website/upload-token -> 403 Forbidden 
```

Here's my woodpecker pipeline if interested:

```yml
pipeline:
  build:
    image: node:alpine
    commands:
      - npm i -g pnpm
      - pnpm i --frozen-lockfile
      - pnpm run build
  deploy:
    image: node:alpine
    secrets: [CLOUDFLARE_ACCOUNT_ID, CLOUDFLARE_API_TOKEN]
    commands:
      - npm i -g wrangler
      - npx wrangler pages publish dist --project-name vapour-website

branches: trunk
```
