### ISSUE TITLE
🐛 BUG: unable to bind kv_namespaces

### ISSUE THREAD

**Issue by imohanvadivel** [cloudflare/wrangler2#2294]
### What version of `Wrangler` are you using?

2.4.4

### What operating system are you using?

Mac

### Describe the Bug

In simple projects without any environment, there seem to be problem with binding kv_namespaces.

My `wrangler.toml` file look like
```toml
name = "my_project"
main = "src/index.ts"
compatibility_date = "2022-11-26"

[vars]
client_id = "xxxx"

kv_namespaces = [
  { binding = "cred", id = "xxxx", preview_id = "xxxx" }
]
```

When I run `wrangler publish`, I get back

```bash
⛅️ wrangler 2.4.4 
-------------------
Your worker has access to the following bindings:
- Vars:
  - client_id: "xxxx"
  - kv_namespaces: [
 {
  "binding": "cred",
  "id": "xxxx",
  "preview_id": "xxxx"
 }
]
Total Upload: 8.33 KiB / gzip: 2.37 KiB
Uploaded worksheet_sync (2.08 sec)
Published worksheet_sync (1.87 sec)
  https://my_project.wxyz.workers.dev
Current Deployment ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx
✨  Done in 8.36s.
```

Everything does looks fine, but when I open up my cloudflare dashboard, there is no kv bound to this worker. And the kv is also not accessible from the `env` variable.

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/49231285/204081651-b9780dda-35b5-421d-ba4b-9bc86cdbd757.png">
