### ISSUE TITLE
workers_dev is ignored

### ISSUE THREAD

**Issue by eidam** [cloudflare/wrangler2#269]
hey! 
Just started playing around wrangler2 and I noticed that `workers_dev = false` is being ignored in case I am trying to deploy a worker without any routes (triggers) enabled. 

My config
```toml
name = "worker-name"
compatibility_date = "2022-01-19"

account_id = "acc-id"
workers_dev = false
```
