### ISSUE TITLE
Cannot create binding for class Controller that is not exported by the script [API code: 10061]

### ISSUE THREAD

**Issue by cullophid** [cloudflare/wrangler2#337]
LOVE THE NEW WRANGLER!
I am getting the same error from both wranger2 and wrangler 1.
It only happens when trying to publish the worker.  npx wrangler publish src/index.ts
npx wrangler dev src/index.ts works fine

src/index.ts:
``` ts
import { createRouter } from './router'
import { time } from './time'
import { Env } from './types'

import { plugins } from './plugins'
import { query } from './query'
import { preview } from './preview'
import { login } from './login'
import { logout } from './logout'
import { page } from './page'

const router = createRouter()

const serveStatic = async (filename: string, env: Env) => {
  const file = await env.STATIC_ASSETS.getWithMetadata<{
    sourceMap?: string
  }>('main.js', {
    type: 'stream',
  })
  return new Response(file.value, {
    headers: {
      'content-type': filename.endsWith('.js')
        ? 'text/javascript'
        : filename.endsWith('.css')
        ? 'text/css'
        : filename.endsWith('.map')
        ? 'application/json'
        : 'text/plain',
      SourceMap: '_toddle/' + file.metadata?.sourceMap ?? '',
    },
  })
}

router.get('/main.js', (req, params, env) => serveStatic('main.js', env))
router.get('/main.js.map', (req, params, env) =>
  serveStatic('main.js.map', env),
)
router.get('/__preview.js', (req, params, env) =>
  serveStatic('__preview.js', env),
)
router.get('/__preview.js.map', (req, params, env) =>
  serveStatic('__preview.js.map', env),
)
router.get('/components.js', (req, params, env) =>
  serveStatic('components.js', env),
)
router.get('/components.js.map', (req, params, env) =>
  serveStatic('components.js.map', env),
)
router.get('/runtime.js', (req, params, env) => serveStatic('runtime.js', env))
router.get('/runtime.js.map', (req, params, env) =>
  serveStatic('runtime.js.map', env),
)

router.get('/hello', (req, params, ctx) => {
  return new Response('hello')
})

router.get('/greet/:name', (req, params, ctx) => {
  return new Response(`hello ${params.name}`)
})

router.get('/branch/:name', (req, params, env) => {
  const controller = env.CONTROLLER.get(env.CONTROLLER.idFromName(params.name))
  return controller.fetch(req)
})

router.get('/plugins.js', plugins)

router.post('/_query/(.*)', query)

router.get('/__preview', preview)
router.get('/_toddle/preview', preview)

router.get('/login', login)
router.get('/logout', logout)
router.all('/(.*)', page)

export default {
  async fetch(request: Request, env: Env, context: ExecutionContext) {
    return await time(`${request.method} ${request.url}`, () =>
      router.handle(request, env),
    )
  },
}

export class Controller {
  state: { storage: KVNamespace; blockConcurrencyWhile: Function }
  value: number
  webSockets: WebSocket[]
  constructor(state: any, env: unknown) {
    this.state = state
    this.value = 0
    this.webSockets = []
    time('Sync state', () =>
      this.state.blockConcurrencyWhile(async () => {
        this.value = Number((await this.state.storage.get('value')) ?? 0)
      }),
    )
  }

  async fetch(req: Request) {
    this.value = this.value + 1
    await this.state.storage.put('value', String(this.value))
    return new Response(`COUNT ${this.value}`)
  }
}

```

wrangler.toml

```toml
name = "worker"
type = "javascript"
zone_id = ""
account_id = ""###"
route = ""
workers_dev = true
compatibility_date = "2022-01-22"
kv_namespaces = [ 
  { binding = "FLAGS", id = "###", preview_id="###" },
  { binding = "PAGES", id = ""###",", preview_id=""###"," },
  { binding = "STATIC_ASSETS", id = ""###",", preview_id=""###"," },
  { binding = "DEFLATED_PROJECTS", id = ""###",", preview_id=""###"," },
]

[durable_objects]
bindings = [
  { name = "CONTROLLER", class_name = "Controller" } # Binding to our DurableObjectExample class
]

[build.upload]
format = "modules"
dir = "dist"
main = "./worker.mjs"


[env.preview]
kv_namespaces = [ 
  { binding = "FLAGS", id = ""###"," },
  { binding = "PAGES", id = ""###"," },
  { binding = "STATIC_ASSETS", id = ""###"," },
  { binding = "DEFLATED_PROJECTS", id = ""###","},
]


[env.preview.durable_objects]
bindings = [
  { name = "CONTROLLER", class_name = "Controller" } # Binding to our DurableObjectExample class
]
```

**Comment by threepointone** [comment]
I'll file a fresh issue that goes into more detail about this, but tl;dr you need to specify a `[migrations]` section in your `wrangler.toml` file. Relevant docs https://developers.cloudflare.com/workers/learning/using-durable-objects#durable-object-migrations-in-wranglertoml. Try adding this: 
```toml
[[migrations]]
tag = "v1"
new_classes = ["Controller"].
```

I'll leave this issue open for now, we'll edit the title later. 

Thanks for trying wrangler2 and filing this issue! Please file issues for anything that looks wrong, or could be improved.
