### ISSUE TITLE
kv:get errors out reading --preview key if key is not in JSON format

### ISSUE THREAD

**Issue by dukejones** [cloudflare/wrangler2#359]
Wrangler 0.0.15

Expected: `kv:get` returns the key requested
Actual: Errors out complaining that it's not JSON
 
```
yarn wrangler kv:key put oracleKey asdflkjsfad --binding pk --preview

yarn wrangler kv:key get oracleKey --binding pk --preview
Failed to fetch /accounts/6fxxxxxxxxxxxxxxx/storage/kv/namespaces/xxxxxxxxxxxxxxxxxx/values/oracleKey - 200: OK
Invalid JSON response:
asdflkjsfad
```

```toml
compatibility_date = "2022-02-01"
kv_namespaces = [ 
  { binding = "pk", id = "xxxxxxxxxxxx", preview_id = "xxxxxxxxxxxxxxxxx" }
]
```
