### ISSUE TITLE
🐛 BUG: Routes in wrangler.toml doesn't respect env

### ISSUE THREAD

**Issue by istarkov** [cloudflare/wrangler2#513]
### What version of `Wrangler` are you using?

0.0.17

### What operating system are you using?

Mac, Linux

## How to reproduce

Create different routes for `production` env in `wrangler.toml` file

```toml
routes = ["example-test.blabla.ch/*"]
[env.production]
routes = ["example.blabla.ch/*"]
```

execute 
```bash
wrangler publish ./src/example.ts --env production --config ./wrangler.toml
```

Worker will be deployed to `example-test.blabla.ch/*` instead of `example.blabla.ch/*`.

This because here https://github.com/cloudflare/wrangler2/blob/9534c7fd1351daacaed63b3a3e2fafa884b515a8/packages/wrangler/src/publish.ts#L303 env params is not used at all (its used for vars, durable objects etc, but not for routes) see `bindings` above.
