### ISSUE TITLE
🐛 BUG: Routes do not work if api token is restricted to zone

### ISSUE THREAD

**Issue by skirsten** [cloudflare/wrangler2#651]
### What version of `Wrangler` are you using?

0.0.0-21ee93e

### What operating system are you using?

Linux

### Describe the Bug

1. Restrict API token to a zone, for example:
```
Account - Workers R2 Storage:Edit, Workers Tail:Read, Workers KV Storage:Edit, Workers Scripts:Edit, Account Settings:Read
    example.com - Workers Routes:Edit
All users - User Details:Read
```

2. Try to deploy to `routes = ["https://example.com/*"]`
3. Error:
```
 ⛅️ wrangler 0.0.0-21ee93e 
---------------------------
Uploaded test-worker (1.71 sec)

✘ [ERROR] Received a bad response from the API

  Authentication error [code: 10000]
```

Not sure if this is related with the zone inference or a bug on Cloudflare's side

**Comment by threepointone** [comment]
Oh interesting. I think this might be a bug on our side. We use a different api for the routes change than wrangler 1; and this scope might not cover it. I'll investigate it this week. Thank you for filing a detailed issue!

**Comment by threepointone** [comment]
I believe the workaround for now is to scope the token to an account and not to a zone, since the api for setting routes is scoped to an account at the moment, and since routes can contains patterns to different zones/domains. We should probably eventually fix this and let it work with zone scoped tokens

**Comment by nathang21** [comment]
Has anyone confirmed the fix for this? I'm using the "Edit Workers" template for the API Token via Github Actions, but this is not working. 

I am able to locally run `npx wrangler publish` without issue, but when deploying via github actions, it fails with this error. 
```
webpack 5.72.1 compiled successfully in 1966 ms
✘ [ERROR] ✘ [ERROR] Received a bad response from the API  
    Authentication error [code: 10000]    
    If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new
```


See below for my config:
wrangler.toml
```
name = "XXX"
main = "dist/worker.js"
account_id = "YYY"
# route =
workers_dev = true
compatibility_date = "2022-05-04"

[build]
command = "npm install && npm run build"
```

ci.yml
```
name: API CI
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
```
