### ISSUE TITLE
🐛 BUG: nonactionable error about migration

### ISSUE THREAD

**Issue by IgorMinar** [cloudflare/wrangler2#705]
### What version of `Wrangler` are you using?

0.0.0-52ea60f

### What operating system are you using?

mac

### Describe the Bug

I tried to publish my worker with a DO and I got this error that puzzles me... I have no idea what to do about this:

```sh
$ wrangler publish
 ⛅️ wrangler 0.0.0-52ea60f 
---------------------------

✘ [ERROR] Received a bad response from the API

  Migration tag precondition failed; current tag is v1 [code: 10079]
```

wrangler.toml
```toml
name = "request-counter"
main = "src/index.ts"
compatibility_date = "2022-03-25"

[[durable_objects.bindings]]
name = "doRequestCounter"
class_name = "DurableRequestCounter"

[[migrations]]
tag = "v1"
new_classes = ["DurableRequestCounter"]
```

Could we improve the error message to be actionable?
