### ISSUE TITLE
Prompt when `kv_namespaces` is defined but not in all environments

### ISSUE THREAD

**Issue by KianNH** [cloudflare/wrangler2#751]
As per https://github.com/cloudflare/cloudflare-docs/issues/3998 which talks about the clarity around `kv_namespaces` not being inherited into environments, I think it'd be beneficial if `wrangler` prompted if there's environments that don't have `kv_namespaces` defined when others do (or if the `kv_namespaces` is in the top-level scope).

As an example, in the below scenario, the `test` environment will not have the binding for the `TODO` namespace.

```toml
name = "worker"

# ...

kv_namespaces = [ 
  { binding = "TODO", id = "06779da6940b431db6e566b4846d64db" }
]

[env.test]
name = "worker-test"
```

Maybe `wrangler` could prompt about this - such as "The `TODO` namespace will not be inherited by the `test` environment. Please define it under this environment if you'd like to bind it." - to give some clarity to the user.

I'm sure there's a better way to word it than I did though :^)
