### ISSUE TITLE
Issue while publishing Worker with crons triggers

### ISSUE THREAD

**Issue by SirCremefresh** [cloudflare/wrangler2#787]
When i run the command `npx wrangler@beta publish main.ts --config wrangler.toml --env development` to publish a worker script i get the following error:
```shell
 ⛅️ wrangler 0.0.25 
--------------------
Uploaded sharecation-authentication-scheduled-development (2.70 sec)

✘ [ERROR] Received a malformed response from the API

  Internal Server Error
  

  PUT
  /accounts/XXXXXXXX/workers/scripts/sharecation-authentication-scheduled-development/schedules
  -> 500 Internal Server Error
  
  If you think this is a bug, please open an issue at:
  https://github.com/cloudflare/wrangler2/issues/new


Error: ./node_modules/.bin/wrangler exited with code 1
    at ChildProcess.<anonymous> (file:///Users/XXXXX/git/sharecation/worker/publish.mjs:38:16)
    at ChildProcess.emit (node:events:520:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

Process finished with exit code 1
```

wrangler.toml
```toml
name = "sharecation-authentication-scheduled"
compatibility_date = "2022-04-01"
usage_model = "unbound"
legacy_env = true

[vars]
ENVIRONMENT = ""

[triggers]
crons = ["0 0 * * mon"]

[env.development]
vars = { ENVIRONMENT = "development" }
kv_namespaces = [
    { binding = "COMMON", id = "XXXX", preview_id = "XXXX" },
    { binding = "AUTHENTICATION", id = "XXXX", preview_id = "XXXX" }
]

[env.production]
vars = { ENVIRONMENT = "production" }
kv_namespaces = [
    { binding = "COMMON", id = "XXXX" },
    { binding = "AUTHENTICATION", id = "XXXX" }
]
```

I change the cli to print the request and result.
request:
> PUT https://api.cloudflare.com/client/v4/accounts/XXXX/workers/scripts/sharecation-authentication-scheduled-development/schedules
object passed to fetch 

```shell
{
  method: 'PUT',
  body: '[{"cron":"0 0 * * mon"}]',
  headers: { 'Content-Type': 'application/json' }
  'Content-Type': 'application/json',
  Authorization: 'Bearer XXXX'
}
```
response:
Body: Internal Server Error
Some response headers:
``` 
 - 'cf-ray', '6faeba6459fb0219-ZRH',
 - 'content-type', 'text/plain; charset=utf-8',
```
