### ISSUE TITLE
Error when trying to publish a worker

### ISSUE THREAD

**Issue by maraisr** [cloudflare/wrangler2#873]
Got the error for the following:
```
✘ [ERROR] Received a bad response from the API

  workers.api.error.zone_not_specified - When using wildcard host ssl for saas entitlement you must
  specify the zone per route using "zone_id" or "zone_name" [code: 10082]
  
  If you think this is a bug, please open an issue at:

```

<details>
<summary>> wrangler.toml</summary>

```toml
name = "my_worker_name"
main = "build/index.mjs"

usage_model = "unbound"

workers_dev = false

route = "https://api.my-domain.com/*"
account_id = "<ignored>"

compatibility_date = "2022-01-01"

[build]
command = "npm run build"

[vars]
ACCOUNT_ID = "<ignored>"

[[kv_namespaces]]
binding = "DATABASE"
id = "<ignored>"
preview_id = "<ignored>"

[miniflare]
port = 8081
kv_persist = true
```

</details>

**Comment by threepointone** [comment]
We need to document this soon, and probably add a more helpful message, but - a route can optionally be an object that includes a `zone_id` or `zone_name`, which is particularly useful when using SSL for SaaS. So in your example, this should work: 

```toml
route = { pattern = "https://api.my-domain.com/*", zone_name = "customer.com"}
# or 
route = { pattern = "https://api.my-domain.com/*", zone_id = "ygidsaf56dfadagfd"}
```

Make sure you're using the lates version of `wrangler@beta`!

Leaving this open, but feel free to close it if the above fixes your problem.
